substitutions:
  devicename: garage

esphome:
  name: $devicename

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret garage_api

ota:
  - platform: esphome
    password: !secret garage_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret garage_ap_ssid
    password: !secret garage_ap_pass

captive_portal:
    
switch:
  - platform: gpio
    name: "Zone 1"
    id: by_relay_1
    pin: 32

  - platform: gpio
    name: "Zone 2"
    id: by_relay_2
    pin: 33

  - platform: gpio
    name: "Zone 3"
    id: by_relay_3
    pin: 25